language: python
sudo: required
dist: trusty

python:
  - '2.7'
  - '3.5'
  - '3.6'

before_install:
  - pip install --upgrade pip setuptools wheel
  - pip install --only-binary=numpy,scipy numpy scipy

install:
  - pip install .
  - pip install nose2

script:
  - cd tests
  - nose2
  - cd ..

deploy:
  provider: pypi
  skip_existing: true
  user: mmatl
  on:
    tags: true
    branch: master
  password:
    secure: dslHpn4e5jvgP5DFQM2Jo+XuODGSFtJ/43tjJ4gTz2FxG/rWH5OhSQNCAzXKSRZrFS8+c93j80836olozplZSLeubBmsZaPRma4EzhVuLQFWiIh803XdQ+Dq6HGSqt+++jHgOUq+8vXm+08iCd54CyEIU1vSNh6YWLoYgjc6r/XTYVUAo6nKO7PeSV7aC31Ftqk2g0jeFy919/roAuLch0q5J/rUkor5aKav4r2VgiFK/7skJ/pnJqHoNYjBUpDwUfjE0XDLIAtI+4Dx78JBsbywlLi2v5/nAnTwOuvWKVpVcWhGg7xE64EO+cZdccbN1DYR8yJx2mJKbxm9VWleytU+JSaXN+1E12xdm3zly7s8IyIzv1VsNiY+QRQfBEV8SUZREuk38I3oLuZD3vhXTOvHgU8uDvoDNEtfRP7Gz2ZuLBWYCsHkjgi2ICe/lJvKGidBwJcxBa7Ev4VSjUhHQNPSweRbUtilguV+RLNmdyCRUbee2mxZ5JpgW/Fh/KDFDsV/RtXkGFfLHS57UbOn7mnDkse8W7z+vQbNiNiKUiA0Wm49bdb5Ldo5TsZjw0Ewyb4EQgKDb984X2UDMm0YeEtQKgN17CVrmPMuUMBu4Bhh42oCWj9ds34otWiej8mKwpa4fg3TW01kz5dNKgA83rMVkrTko9jApfHR90R8Hew=
  distributions: sdist bdist_wheel

notifications:
  email: false
