language: python
sudo: required
dist: trusty
python:
- '2.7'
- '3.5'
- '3.6'
before_install:
- pip install --upgrade pip setuptools wheel
- pip install --only-binary=numpy,scipy numpy scipy
install:
- pip install .
- pip install nose2
script:
- cd tests
- nose2
- cd ..
deploy:
  provider: pypi
  skip_existing: true
  user: mmatl
  on:
    tags: true
    branch: master
  password:
    secure: WQacbTFtcA0fCPIWOI4RPZrnsPgXW+bnaOKamxpIFAja03dock+Q/85hQPaXlBWuTpaZoTMEAafZ/wY9N11TiT9fRSBcIUjSa/S/4+R4/oiJqcvpQ7zlPVYhrVE7V3j146TfnIKAuZZIKqLoh2Q3b++RWOTELqb4+Ds/ejjt/Igl+NH1qtctkbXcIl1bdShYdmx8b6B+JnDggsAVPfsCQWsnEAQgerU96lfiRo4Y5lPjZ0QnIneRgC/xIHpoUf8GYdxSaj/2zOskIJewOs2tSkcVgLylfQS9PcNiwm5bKp3jb5/O7eFyVJzi4rTTJpqlntidndJRKT123rfwvUL6e5i66Uzyefyi4GnnNT5Cemf59OuTR0W9Pej8z2ZdXOoyLhnNe7iHEK8BDT1E6+8ZxLAD88bzeQL9oM2bjxprwuVxRJXTXkNu/PDDZpWG8lxisIycvAieRL3xBiUsjPz9gUVmq8Du4BRj9SBvnooBNR8+RAy6DU/JYSBrWT+w8u2BC+nIdwxc3yhr7dkoQCT//fixlv08c6OLxGSig4y++/BMW+WikYu6sxvyZaC/yFw3t2wKyNCCG1/QTuLhT0EwHaFq6KvpXttkJnRZOlVmtzUO8facg1mCl+JSZUt2+NOdlNqhh3ffptaeesR58jph0wG0v7ZCkbE3+mU7xxJ++n0=
  distributions: sdist bdist_wheel
notifications:
  email: false
