language: python
sudo: required
dist: trusty
python:
- '2.7'
- '3.5'
- '3.6'
before_install:
- pip install --upgrade pip setuptools wheel
- pip install --only-binary=numpy,scipy numpy scipy
install:
- pip install .
- pip install nose2
script:
- cd tests
- nose2
- cd ..
deploy:
  provider: pypi
  skip_existing: true
  user: mmatl
  on:
    tags: true
    branch: master
  password:
    secure: P8R0VnqJ3v8qy/FrprQRMvcmDR/3Az9Fd7SvmhJQ07e9AnQOeAbaTaxfuqh/eAu/Q5PEwxuIK7ZMHlaVEU3GqZgJHRvPE/obibmSbgRuGIjsUzbUTVuUv3w38g5VRoPT5v/TFeCbHdLBg8E70t8MkLE57vU8w9PUOcobMGT2I0y3YxX3e3rRznCxzpqBKLnjZEZMRUa5LnoF9vOnZkra+zsyc0UvEUlPF5Oqt52aQM2V1u+ORhzeGeq3NSk6qolt2utyaf0Omtt2V3KFC9rV71f6RT4Bm4eprL33INhokiU8LPUNovB65begnkpbxXTTfezgAD1zfkel275Sb/aTtMtSMnulEiLB+KsO0/NqSwTDn3BgWnKetLC+9r2/SAfszyLmbHX3rFpzS4Jt8l7l41fSF7FRK9L1JExhN9/JwfYk6QHYAgftuoRi3QxxbeQw5Vhug1vMOPVQYpwtjUIjrIfjext59PybMqMR0R29VPnvIp3SIjOdddN8oRDoHYvR7trOwUXU5+cXalsQy74TMdzNSB2Yy52gSKiw2KJx/FJqhWKTR/bE98fTKpZGSRH10vyafORrodBg0AqJGgQEe25QP26EgvrLsdG531QnJR56KVXjvxRx4rKeN+5UN6te21NO+DMjNnc2Mo/bZNwERtrXnWH7m2tZGZDRWRLr+tI=
  distributions: sdist bdist_wheel
notifications:
  email: false
