language: python
sudo: required
dist: trusty

python:
  - '2.7'
  - '3.5'
  - '3.6'

before_install:
  - pip install --upgrade pip setuptools wheel
  - pip install --only-binary=numpy,scipy numpy scipy

install:
  - pip install .
  - pip install nose2

script:
  - cd tests
  - nose2
  - cd ..

deploy:
  provider: pypi
  skip_existing: true
  user: mmatl
  on:
    tags: true
    branch: master
  password:
    secure: mhx4h9pUewT3Wl61mfcIco9Ja3sV6MMGShBBSSA7XquuJi70e90/Qpkfk+izE+IuO7MgXnPABz1XMLsCmIXmUJO3WSpD8N7aJIyCfGiLeV93YvS5ElXbc5IdQ7b05sFM4iNKglfJNTEQmwIXT09VODZhbWlgkjgW9OwvGF+QDTZgzPZBNQJx1d3+b7PbsnPwGdiPqVPTvaNmEj/KXhwvXSKS2Jg1X1d9Vz/oy3vUO+jJLhNyCvnUfX3awKch5PhSOomhv6Idz5eucEDVN7CjJ2zD2Z9TVh1RNP5t2/rgkMZr7YFzCp6Joc2+qhaymVn745+ZPA1okL2B8WDULMQUoT5varffhnfQtli7uj6QJvAd6ASF4zBcM5JYR+RNCix2qHbvPjGyKP5sY6vrcYb8qmUCHURR43pzYCYNPUWVbO2rNayWzbgkMJE1FuW9M6V6ivUyfpBNqsgz7+P3h1bnCaZ07ErFU3DhScrodOMikcRubBnDM7bkFRu7C/p0eMRk+neXQJuYBjQBIbLuTBrSzrrOJo9RAwGCkZYPvbtrqWuLhOohAUGqkCqAWbyrGMDxVX464ZUORdJWTH7yWErw/Lcnuq9EFbbOaiNrhk1YfgvCoFkHiRhaWL1KEajLWbJHdmlQOVAj0H53ILn3i7imN7lS+GhetlaIeU2tH0KuOn8=
  distributions: sdist bdist_wheel

notifications:
  email: false
